### ISSUE TITLE
H264文件推流

### ISSUE THREAD

**Issue by mahxn0** [PHZ76/RtspServer#1]
你好，我现在调用nvidia TX1的api实现了两路usb视频的编码，编码数据是h264，应该怎么调用你这个程序b把编码好的数据推成rtsp流呢    我编译后运行test 提示如下：

nvidia@tegra-ubuntu:~/RtspServer$ ./test 
[DEBUG] [src/xop/TcpSocket.cpp:bind:27]  <socket=6> bind <192.168.1.8:554> failed.
rtsp://192.168.1.8/live

**Comment by PHZ76** [comment]
打印提示绑定失败, 是不是本地554端口被其它进程占用了? 在example 把RtspServer server(eventLoop.get(), ip, 554);  端口修改一下。这个example可以验证RTSP过程，实时数据流要用pushframe送进去。

**Comment by PHZ76** [comment]
如果需要进行文件推送，可以通过ffmpeg进行帧读取再发送。
