### ISSUE TITLE
多线程回调问题(rtsp_h264_file.cpp示例）

### ISSUE THREAD

**Issue by xuhe018** [PHZ76/RtspServer#11]
您好，在以rtsp_h264_file.cpp进行调试时，发现MediaSession.cpp中的
bool MediaSession::addMediaSource(MediaChannelId channelId, MediaSource* source)
函数本身是被主线程调用的，
而其内部的实现，回调函数source->setSendFrameCallback([this](MediaChannelId channelId, RtpPacket pkt)
实际上却是被子线程进行调用的。
而且函数内部没有加锁，额，这就造成我知识的盲区。我暂时理解是，因为主线程调用一次后就不再进行调用，所以就不需要进行加锁了，但我没有在其他地方看到类似的使用方法，不知道这样使用是否会有其他问题呢，还望您有空时指点一二，谢谢了

**Comment by PHZ76** [comment]
你好，对的，addMediaSource必须在pushFrame之前调用，根据MediaSession的类型调用一次或两次，所以不需要加锁。
