### ISSUE TITLE
不带用户名密码认证

### ISSUE THREAD

**Issue by lilei-John** [PHZ76/RtspServer#13]
没看到支持

**Comment by PHZ76** [comment]
是的，目前还没支持。这几天是假期，我抽空加一下这个功能，完成以后我在这里回复你。

**Comment by PHZ76** [comment]
RTSP服务器已经支持摘要认证。

example:
...
server.setAuthConfig("-_-", "admin", "12345");
...

**Comment by lilei-John** [comment]
厉害👍🏻



---原始邮件---
发件人: "PHZ"<notifications@github.com&gt;
发送时间: 2019年10月9日(星期三) 下午2:55
收件人: "PHZ76/RtspServer"<RtspServer@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"David.Li"<foxmaillu@qq.com&gt;;
主题: Re: [PHZ76/RtspServer] 不带用户名密码认证 (#13)



RTSP服务器已经支持摘要认证。
 
example:
 ...
 server.setAuthConfig("-_-", "admin", "12345");
 ...
