### ISSUE TITLE
我对 example/rtsp_server.cpp 进行了这样的修改为什么obs连不上了呢

### ISSUE THREAD

**Issue by buzai** [PHZ76/RtspServer#15]
std::string ip = "0.0.0.0";//xop::NetInterface::getLocalIPAddress(); //获取网卡ip地址
  std::string rtspUrl;

    std::shared_ptr<xop::EventLoop> eventLoop(new xop::EventLoop());
    xop::RtspServer server(eventLoop.get(), ip, 5544);  //创建一个RTSP服务器

**Comment by PHZ76** [comment]
你好，这个应该跟OBS没啥关系吧，我记得OBS是一个RTMP推流器。你可以使用VLC点播rtsp://ip:5544/live 试试
