### ISSUE TITLE
Length of RTP timestamp will be greater then unsigned int

### ISSUE THREAD

**Issue by roywu01** [PHZ76/RtspServer#17]
Thanks for sharing.
This project is very powerful.

I found 1 issue that cause the stream can't be played.

`chrono::time_point_cast<chrono::microseconds>(chrono::steady_clock::now());`

The value of this function will be greater and greater.
Finally it will be greater than 32 bits, so some player can't play the stream.

**Comment by PHZ76** [comment]
Hi, I think it should be handled by the rtsp client.

// rtsp client handle rtp timestamp
int64_t modify_timestamp(uint32_t timestamp)
{
	static int64_t relative_timestamp = 0;
	static int64_t last_timestamp = 0;
		
	if(last_timestamp == 0)
	{
		last_timestamp = (int64_t)timestamp;
	}
	
	int64_t current_timestamp = (int64_t)timestamp;
	int64_t delta_timestamp = last_timestamp - current_timestamp;
	
	if(delta_timestamp > 0)
	{
		relative_timestamp += delta_timestamp;
	}
	
	last_timestamp = (int64_t)timestamp;
	return relative_timestamp;
}

**Comment by PHZ76** [comment]
Hi, I think it should be handled by the rtsp client.

int64_t modify_timestamp(uint32_t timestamp)
{
	static int64_t relative_timestamp = 0;
	static int64_t last_timestamp = 0;
		
	if(last_timestamp == 0)
	{
		last_timestamp = (int64_t)timestamp;
	}

	int64_t current_timestamp = (int64_t)timestamp;
	int64_t delta_timestamp = last_timestamp - current_timestamp;

	if(delta_timestamp > 0)
	{
		relative_timestamp += delta_timestamp;
	}

	last_timestamp = (int64_t)timestamp;
	return relative_timestamp;
}

**Comment by PHZ76** [comment]
Hi, I think it should be handled by the rtsp client.

`int64_t modify_timestamp(uint32_t timestamp)
{
static int64_t relative_timestamp = 0;
static int64_t last_timestamp = 0;

if(last_timestamp == 0)
{
	last_timestamp = (int64_t)timestamp;
}

int64_t current_timestamp = (int64_t)timestamp;
int64_t delta_timestamp = last_timestamp - current_timestamp;

if(delta_timestamp > 0)
{
	relative_timestamp += delta_timestamp;
}

last_timestamp = (int64_t)timestamp;
return relative_timestamp;
}`

**Comment by roywu01** [comment]
Hi, thanks for your reply
In fact, I'm developing on a smart home camera for Alexa.
Alexa echo show doesn't handle such situation, so I need to handle this on server side.

I have fixed this by modifying the function "getRtpInfo" in "RtpConnection.cpp".
I set rtptime as 0 when the stream initiated.
Just want to share this with you.

Thanks. :)
