### ISSUE TITLE
rtsp_h264_file例子的使用

### ISSUE THREAD

**Issue by zz001001** [PHZ76/RtspServer#19]
博主你好，请问你这个rtsp_h264_file的例子要怎么使用呢？我使用VLC播放器无法连接和打开rtsp_h264_file例子中的test.h264文件。新手求教，万分感谢

**Comment by PHZ76** [comment]
你好，rtsp_h264_file 这个demo运行启来后，如果没有出现端口被占用的情况，控制台会打印一个rtsp url，使用VLC打开网络串流，就可以看到视频文件的画面。

**Comment by zz001001** [comment]
十分感谢博主的解答，demo已成功运行，还有一个问题想请问一下，就是这个RtspServer能够处理来自客户端推送的音视频流吗？




发自网易邮箱大师
在2019年11月21日 18:41，PHZ<notifications@github.com> 写道：

你好，rtsp_h264_file 这个demo运行启来后，如果没有出现端口被占用的情况，控制台会打印一个rtsp url，使用VLC打开网络串流，就可以看到视频文件的画面。

**Comment by PHZ76** [comment]
这是服务器，没有客户端功能
