### ISSUE TITLE
测试rtsp_h264_file遇到的一些问题

### ISSUE THREAD

**Issue by ouweibin** [PHZ76/RtspServer#21]
你好，我在测试rtsp_h264_file遇到的一些问题
1、Makefile第一行DEUBG = -DXOP_DEBUG是不是应该改为DEBUG = -DXOP_DEBUG，还有我查找了整个仓库并没有找到XOP_DEBUG这个编译开关使用的地方；
2、我修改了/src/net/Logger.h头文件后重新make，没有响应，而是要make clean后再重新make，是不是Makefile里没有支持追踪头文件；
3、bind失败后LOG_DEBUG没有打印成功，发现LOG_DEBUG的实现需要定义_DEBUG宏，但是该宏在Makefile没有出现，我在Makefile里定义该宏后问题还是没有解决，是不是跟Makefile里没有支持追踪头文件有关？我把_DEBUG宏开关相关代码删除后，LOG_DEBUG能够正常打印；

**Comment by PHZ76** [comment]
1.  XOP_DEBUG 是以前代码使用的宏，后面去掉了。
2.  没有。
3.  是的，LOG_DEBUG需要宏定义，我后面一直在windows下用VS调试, 一直没有注意，谢谢你，后面我会改成LOG_ERROR。
