### ISSUE TITLE
关于readFrame

### ISSUE THREAD

**Issue by o-u-p** [PHZ76/RtspServer#25]
大神
```
if (((m_buf[i + startCode] & 0x1F) == 0x5 || (m_buf[i + startCode] & 0x1F) == 0x1) &&
			((m_buf[i + startCode + 1] & 0x80) == 0x80))
		{
			bFindStart = true;
			i += 4;
			break;
		}
```

为什么这里只判断1和5啊， 2,3,4不是么?(抱歉刚开始学习这个^_^|||)

**Comment by PHZ76** [comment]
这里只判断一般的 NAL 类型。

**Comment by Gabygaojia** [comment]
你好  这个(m_buf[i + startCode + 1] & 0x80) == 0x80) 是在判断什么？

**Comment by Gabygaojia** [comment]
> 这里只判断一般的 NAL 类型。

(m_buf[i + startCode + 1] & 0x80) == 0x80) 这个是在判断什么？

**Comment by Gabygaojia** [comment]
> 这里只判断一般的 NAL 类型。

请问一下 (m_buf[i + startCode + 1] & 0x80) == 0x80) 这个是在判断啥？ 谢谢
