### ISSUE TITLE
推h265流的时候播放器无法播放

### ISSUE THREAD

**Issue by Chenling1997** [PHZ76/RtspServer#26]
在H265Source的handleFrame里面
应该先把头部的（00 00 00 01）去掉再计算naluType 所以应该加在获取frameBuf和framesize之后减去相应的数据。
 uint8_t *frameBuf  = frame.buffer.get();
 uint32_t frameSize = frame.size;
 frameBuf +=4;
 frameSize-=4;

**Comment by PHZ76** [comment]
应该在构建videoframe的时候去掉，转发和推流可以不一样。

**Comment by Chenling1997** [comment]
嗯，因为碰到了就和您说一下。 我是直接获取h265帧数据然后pushframe&nbsp; 所以计算的时候是带着0001的头的 。 谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PHZ"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午5:35
收件人:&nbsp;"PHZ76/RtspServer"<RtspServer@noreply.github.com&gt;;
抄送:&nbsp;"506753922"<506753922@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PHZ76/RtspServer] 推h265流的时候播放器无法播放 (#26)




应该在构建videoframe的时候去掉，转发和推流可以不一样。
