### ISSUE TITLE
关于std c++11

### ISSUE THREAD

**Issue by miaoweijun** [PHZ76/RtspServer#3]
使用了std c++11,嵌入式系统上交叉编译环境，很多不支持std c+11,肯定会限制在嵌入式系统的应用

**Comment by PHZ76** [comment]
谢谢你的建议，我一开始设计的时候也不单单考虑到嵌入式平台，以后可能会作为流媒体服务器的一部分。我当时的应用是运行在海思Hi3516a平台上的，SDK支持c++11。
