### ISSUE TITLE
May memory leak using shared_ptr to manage array?

### ISSUE THREAD

**Issue by 7oud** [PHZ76/RtspServer#31]
https://github.com/PHZ76/RtspServer/blob/ee371b63042404f5f346575c7e2fb8ec5f6a5a11/src/xop/rtp.h#L66-L72

May leads to memory leak, use deleter instead?
```
RtpPacket() 
	: data(new uint8_t[1600], std::default_delete<uint8_t[]>()) 
{ 
	type = 0; 
} 
std::shared_ptr<uint8_t> data; 
```

**Comment by 7oud** [comment]
Could you fix this problem? [Ref](https://stackoverflow.com/questions/13061979/shared-ptr-to-an-array-should-it-be-used)

**Comment by pfeatherstone** [comment]
Yep that looks like a massive memory leak.

**Comment by pfeatherstone** [comment]
@7oud you could submit a quick PR

**Comment by pfeatherstone** [comment]
I've submitted a PR

**Comment by pfeatherstone** [comment]
This has been fixed now
