### ISSUE TITLE
Send image bufffer frame failed

### ISSUE THREAD

**Issue by yuchenglong** [PHZ76/RtspServer#32]
I used rtsp_server sample and sent stream images convert by cv::mat, but failed.  
Vlc.exe can not play my rtsp stream

**Comment by elevenface** [comment]
H264Source.cpp  line 53
uint8_t* frame_buf  = frame.buffer.get() + 4;
uint32_t frame_size = frame.size - 4;

**Comment by hongson23** [comment]
> I used rtsp_server sample and sent stream images convert by cv::mat, but failed.
> Vlc.exe can not play my rtsp stream

Hello, do you resolved this problem? If that was resolved so please take some codes for detail solution
thanks

**Comment by elevenface** [comment]
you must convert cv:mat to YUV format,encode h264/h265 and include frame
head like 00 00 00 01, input rtspServer ringbuf ,try again

Hoàng Hồng Sơn <notifications@github.com> 于2020年11月1日周日 下午9:45写道：
