### ISSUE TITLE
android移植

### ISSUE THREAD

**Issue by GongKuiJun** [PHZ76/RtspServer#33]
你好 我把他移植到Android平台，Server 能开启 ，能进行TCP连接，但是回调函数无法执行，请问是什么是什么原因导致的。

**Comment by PHZ76** [comment]
你好，我没有试过在安卓平台编译，但是以前在嵌入式平台使用过，应该没什么问题。你可以看看编译器版本对C++11的支持情况

**Comment by GongKuiJun** [comment]
我编译了 能支持 但是无法开启

**Comment by GongKuiJun** [comment]
非常感谢，能进行Android移植了 也测试通过了，但是遇到一个奇怪的问题，当手机在充电的情况下，网络能正常使，当断开USB连接后，过一段时间网络资源被回收了，无法继续使用，请问是网络库哪里有什么需要设置的么？

**Comment by lvjiong** [comment]
> 你好 我把他移植到Android平台，Server 能开启 ，能进行TCP连接，但是回调函数无法执行，请问是什么是什么原因导致的。

你好，你的问题解决了吗。我在Android上也是可以连接，但很快就disconnect了
