### ISSUE TITLE
replace with pthread_create

### ISSUE THREAD

**Issue by tolaai** [PHZ76/RtspServer#40]
Dear All,
in EventLoop.cpp has code as :
_std::shared_ptrstd::thread thread(new std::thread(&TaskScheduler::Start, task_scheduler_ptr.get()));
thread->native_handle();
threads.push_back(thread);_
How can I replace with pthread_create ? Please tell me way to use.
Thanks you

**Comment by PHZ76** [comment]
Hi, The compiler must support cpp11.
