### ISSUE TITLE
RTSP推送出现no data received

### ISSUE THREAD

**Issue by deansay** [PHZ76/RtspServer#7]
通过ADB将ARM板上的554端口映射到主机本地，VLC可以正常登录服务器、播放、停止。
但是数据貌似有些问题，出现如下问题：

[000055de44a665b0] main playlist: playlist is empty
Created new TCP socket 37 for connection
Created new TCP socket 37 for connection
[00007f8ed80010f0] live555 demux error: no data received in 10s, aborting

代码中我没有打包音频数据，使用的RTSPDemo

注释掉了音频的通道：
```
    // 添加音视频流到媒体会话, track0:h264, track1:aac
    session->addMediaSource(xop::channel_0, xop::H264Source::createNew());
    //session->addMediaSource(xop::channel_1, xop::AACSource::createNew(44100,2));
    //session->startMulticast(); // 开启组播(ip,端口随机生成), 默认使用 RTP_OVER_UDP, RTP_OVER_RTSP
```
所以打包推送的时候也没有打包音频数据。

```
        xop::AVFrame vidoeFrame(nval + 1024);
        vidoeFrame.size = 0;
        vidoeFrame.type = xop::VIDEO_FRAME_P;
        vidoeFrame.timestamp = xop::H264Source::getTimeStamp();
        log(_debug, "%x %x %x %x %x", data[0],data[1],data[2],data[3],data[4]);

        if (data[4] == 0x65) //0x67:sps ,0x65:IDR
        {
            //添加sps, pps
            char tmpbuf[128] = {};
            char *ptmpbuf = tmpbuf;

            size_t size = sizeof(tmpbuf);
            uint32_t flag = 0;

            ipc_vget(ipc_ctx, "H264_SPSPPS", 11 ,tmpbuf,&size,&flag);
            memcpy(vidoeFrame.buffer.get(), ptmpbuf + 4, size - 4); // +4去掉H.264起始码
            vidoeFrame.size += size -4;

            memcpy(vidoeFrame.buffer.get() + vidoeFrame.size,val, nval);
            vidoeFrame.size += nval;

        }
        else
        {
            memcpy(vidoeFrame.buffer.get(), val+4, nval-4); // +4去掉H.264起始码
            vidoeFrame.size += (nval-4);
        }

        rtspServer->pushFrame(sessionId, xop::channel_0, vidoeFrame); //送到服务器进行转发, 接口线程安全

```
请问还有哪里参数需要设置吗？ 或者是必须要发送音频数据吗？

**Comment by PHZ76** [comment]
推送I帧使用vidoeFrame.type = xop::VIDEO_FRAME_I; 
如果不想使用帧类型判断 vidoeFrame.type填0

**Comment by PHZ76** [comment]
时间戳有问题，修改代码 使用 gettimeofday 试试。另外，如果播放失败可以尝试不去掉起始码。

uint32_t H264Source::getTimeStamp()
{
 #if defined(__linux) || defined(__linux__)
	struct timeval tv = {0};
	gettimeofday(&tv, NULL);
	uint32_t ts = ((tv.tv_sec*1000)+((tv.tv_usec+500)/1000))*90; // 90: _clockRate/1000;
	return ts;
#else  
	//auto timePoint = chrono::time_point_cast<chrono::microseconds>(chrono::steady_clock::now());
	//return (uint32_t)((timePoint.time_since_epoch().count() + 500) / 1000 * 90 );
#endif
}

**Comment by deansay** [comment]
我确认了一下时间戳，大概每帧数据到达时间约2.7ms(2700), 还是出现了 ES_OUT_SET_(GROUP_)PCR  is called too late的错误。

VLC设置的缓存：300ms

VLC 日志：
```
[00007fcb680010f0] live555 demux error: keep-alive failed: liveMedia3
[00007fcb70000c40] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 300 ms)
[00007fcb6800c9e0] main decoder error: Timestamp conversion failed for 1546503949115982: no reference clock
[00007fcb6800c9e0] main decoder error: Could not get display date for timestamp 0
[00007fcb6800c9e0] main decoder error: Timestamp conversion failed for 1546503949115982: no reference clock
[00007fcb6800c9e0] main decoder error: Could not convert timestamp 0 for FFmpeg
```
RTSP SERVER 日志：
```
2010-01-01 00:02:45.619832 DEBUG 6800 [ipc_message_recv:48] 0 0 0 1 41  timestamp 1194959304 time: 2700
2010-01-01 00:02:45.650434 DEBUG 6800 [ipc_message_recv:48] 0 0 0 1 41  timestamp 1194962004 time: 2700
2010-01-01 00:02:45.680760 DEBUG 6800 [ipc_message_recv:48] 0 0 0 1 41  timestamp 1194964794 time: 2790
2010-01-01 00:02:45.710254 DEBUG 6800 [ipc_message_recv:48] 0 0 0 1 41  timestamp 1194967404 time: 2610
[rtsp://0.0.0.0/live] Online: 0
```

**Comment by PHZ76** [comment]
系统是大端序？ 如果可以用wireshark抓一下rtp包，看能否正常显示rtp包的信息。

**Comment by deansay** [comment]
系统是ubuntu 18.04 应该是小端吧，我抓包试试看看数据传送是否正确。

**Comment by deansay** [comment]
非常感谢，现在问题已得到解决，反馈一下：

1. Linux的时间戳转换有些问题，会出现时间比较前一帧晚的情况，应该是转换时丢掉了一些。
修改如下：
```c
	struct timeval tv = {0};
	gettimeofday(&tv, NULL);
        uint32_t ts = (tv.tv_sec * 1000000 + tv.tv_usec) / 1000 * 90;
	return ts;
```
2. vlc播放rtsp over tcp画面突然卡住问题
提示： live555 demux error: keep-alive failed: liveMedia3
因为vlc每隔一定时间除了会发送OPTIONS命令，然后还有以’$’开头的一串特殊字节，发送完这个播放画面就卡住了。

关于$数据说明，下面有些介绍。
https://blog.csdn.net/myslq/article/details/79819179

这个问题仅在VLC 3.0.5之前版本出现。
所以解决办法有两种：
1. 在rtsp服务器针对’$’开头数据做些处理。
2. 升级VLC 到3.0.5 版本。
```
   sudo snap install vlc
```

**Comment by PHZ76** [comment]
非常感谢你，解决了问题并给出了解决方案。我一直使用VLC 3.0.3版本做测试，没有出现过rtsp over tcp卡住的问题，我会抽空再分析一下这个情况，尝试修复这个问题。

**Comment by deansay** [comment]
了解，我这边出现问题的版本是VLC 3.0.4，修改了下上个描述以免误导。
给赞。

**Comment by PHZ76** [comment]
抱歉，现在才想起这个问题。。。VLC3.0.4使用Option做心跳包，原先的处理是带有RTCP包标志的数据全部丢弃，因为没有处理好，导致Option包也丢弃了。目前已修复了这个问题，非常感谢你的反馈。
