### ISSUE TITLE
长时间运行，服务端无法接受新客户端连接请求

### ISSUE THREAD

**Issue by BreakingY** [PHZ76/RtspServer#80]
客户端频繁与服务端断开并重连服务端会出现很多CLOSE_WAIT状态或者用netstat看Recv-Q不断增长，但无法accept到新连接，长时间运行这个bug基本上是必现的，请问大佬有解决这个bug吗

**Comment by yukuilong** [comment]
请问这个问题 最后怎么解决的 ？
